server:
  port: 10021
spring:
  application:
    name: microservice-consumer-feign
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.52.101:10001/eureka,http://192.168.52.102:10001/eureka,http://192.168.52.103:10001/eureka
