server:
  port: 10010
spring:
  application:
    name: microservice-provider-system
eureka:
  instance:
    #自定义服务名称信息
    instance-id: microservice-provider-system
    #显示IP地址
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
