server:
  port: 10010
spring:
  application:
    name: microservice-provider-system
eureka:
  instance:
    #自定义服务名称信息
    instance-id: microservice-provider-system
    #显示IP地址
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://192.168.52.101:10001/eureka,http://192.168.52.102:10001/eureka,http://192.168.52.103:10001/eureka
#服务信息
info:
  app.name: microservice-parent
  company.name: www.xxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
