server:
  port: 10003

spring:
  application:
    name:  microservice-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:wangbin-repository/microservice-config.git #GitHub\u4E0A\u9762\u7684git\u4ED3\u5E93\u540D\u5B57
